# This template defines velocity and acceleration limits for all robot joints.
# Template variable <robot_prefix> is replaced at launch time.

default_velocity_scaling_factor: 0.60
default_acceleration_scaling_factor: 0.60

joint_limits:
  # ARM JOINTS
  <robot_prefix>joint_1:
    has_velocity_limits: true
    max_velocity: 1.6000000000000001
    has_acceleration_limits: true
    max_acceleration: 1.0
  <robot_prefix>joint_2:
    has_velocity_limits: true
    max_velocity: 1.6000000000000001
    has_acceleration_limits: true
    max_acceleration: 1.0
  <robot_prefix>joint_3:
    has_velocity_limits: true
    max_velocity: 1.6000000000000001
    has_acceleration_limits: true
    max_acceleration: 1.0
  <robot_prefix>joint_4:
    has_velocity_limits: true
    max_velocity: 1.6000000000000001
    has_acceleration_limits: true
    max_acceleration: 1.0
  <robot_prefix>joint_5:
    has_velocity_limits: true
    max_velocity: 1.6000000000000001
    has_acceleration_limits: true
    max_acceleration: 1.0
  <robot_prefix>joint_6:
    has_velocity_limits: true
    max_velocity: 3.2000000000000002
    has_acceleration_limits: true
    max_acceleration: 1.0

  # GRIPPER JOINTS

  <robot_prefix>left_finger_bottom_joint:
    has_velocity_limits: true
    max_velocity: 0.59999999999999998
    has_acceleration_limits: true
    max_acceleration: 0.3
  <robot_prefix>left_finger_tip_joint:
    has_velocity_limits: true
    max_velocity: 1000.0
    has_acceleration_limits: true
    max_acceleration: 0.3
  <robot_prefix>right_finger_bottom_joint:
    has_velocity_limits: true
    max_velocity: 0.59999999999999998
    has_acceleration_limits: true
    max_acceleration: 0.3
  <robot_prefix>right_finger_tip_joint:
    has_velocity_limits: true
    max_velocity: 1000.0
    has_acceleration_limits: true
    max_acceleration: 0.3