hardware:
  robot_ip: 192.168.1.10
  username: admin
  password: admin
  port: 10000
  port_realtime: 10001
  session_inactivity_timeout_ms: 6000
  connection_inactivity_timeout_ms: 2000
  use_internal_bus_gripper_comm: true
  gripper_joint_name: 'right_finger_bottom_joint'
  gripper_max_velocity: 100.0
  gripper_max_force: 100.0